services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: teamsight
      POSTGRES_PASSWORD: InsecureLocalPassword
      POSTGRES_USER: teamsight
    ports:
      - "5432:5432"
    volumes:
      - teamsight_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

  frankenphp:
    build:
      context: .
      dockerfile: Dockerfile
      target: frankenruntime
    environment:
      FRANKENPHP_CONFIG: "worker ./public/index.php"
      APP_RUNTIME: "Runtime\\FrankenPhpSymfony\\Runtime"
    volumes:
      - .:/app
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    # commentez la ligne suivante en production, elle permet d'avoir de beaux logs lisibles en dev
    tty: true

###> symfony/mailer ###
  # mailer:
  #   image: axllent/mailpit
  #   ports:
  #     - "1025"
  #     - "8025"
  #   environment:
  #     MP_SMTP_AUTH_ACCEPT_ANY: 1
  #     MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###

volumes:
###> doctrine/doctrine-bundle ###
  teamsight_data:
###< doctrine/doctrine-bundle ###
